[package]
name = "hyperx-overlay"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31"
hidapi = { version = "2", default-features = false, features = ["windows-native"] }
windows = { version = "0.58", features = ["Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }

[profile.release]
opt-level = "s"
strip = true
